### PR TITLE
Implement better Result type

### PR DESCRIPTION
**Pull request by picatz**
This is a (work-in-progress) PR that aims to fix https://github.com/subfinder/research/issues/1

### CODE REVIEW

**Comment by codingo** [comment]
Solid work!

**Comment by Mzack9999** [comment]
I definitely like this

**Comment by Ice3man543** [comment]
Great work.

**Comment by picatz** [comment]
Going to look over this once more (right now this morning) and then merge the new `Result` struct. 👍

**Comment by picatz** [comment]
### Before Merging
I'm going to add tests for the `Printable()`, `IsPrintable()`, `Print()`, and `JSON()` functions that aren't just Examples ( which are actually tests still ). 

That way _**everything**_ has a test _**and**_ an example.

**Comment by picatz** [comment]
😂 I love how I just realized the `IsPrintable()` function I wrote has basically _no_ way for it to return false, ever. Might remove that. The `Print()`function, I think, is really only useful for debugging at the moment anyway. 

It can also be re-worked or added back later when _actually_ needed.

**Comment by picatz** [comment]
# Fix Empty Result Logic (`&Result{}`)
One thing I noticed is that `result := &Result{}` ( an empty result, that has not been filled ) has a "zero value" in a sense with the default effect being a "success" when the `result.IsSuccess()` method is called on it by returning `true`.

My solution is going to be to have the `result.IsSuccess()` method only return `true` when there's a `Success` value (string greater than 0) and the `Failure` is `nil`.

lol

**Comment by picatz** [comment]
This should solve our problems nicely, I think.
https://play.golang.org/p/OwQUoohP2rn

**Comment by picatz** [comment]
# Benchmark Results 
> **Note:** 🤷‍♂️ Benchmarks are weird, but sometimes helpful.
```
goos: darwin
goarch: amd64
```
```
BenchmarkResultGetTypeThreadSafe-8                          	30000000	        56.7 ns/op
BenchmarkResultGetTypeThreadSafeMultiThreaded-8             	 5000000	       285 ns/op
BenchmarkResultGetType-8                                    	2000000000	         1.54 ns/op
BenchmarkResultGetTypeMultiThreaded-8                       	 5000000	       311 ns/op
BenchmarkNewResultSingleThreaded-8                          	20000000	        87.9 ns/op
BenchmarkNewResultMultiThreaded-8                           	 5000000	       309 ns/op
BenchmarkInitializeEmptyResultSingleThreaded-8              	2000000000	         0.30 ns/op
BenchmarkInitializeSuccessResultSingleThreaded-8            	300000000	         4.55 ns/op
BenchmarkInitializeEmptyPointerToResultSingleThreaded-8     	500000000	         3.05 ns/op
BenchmarkInitializeSuccessPointerToResultSingleThreaded-8   	300000000	         4.59 ns/op
BenchmarkInitializeEmptyResultMulitThreaded-8               	 5000000	       311 ns/op
BenchmarkInitializeSuccessResultMulitThreaded-8             	 5000000	       318 ns/op
BenchmarkInitializeEmptyPointerToResultMulitThreaded-8      	 5000000	       308 ns/op
BenchmarkInitializeSuccessPointerToResultMulitThreaded-8    	 5000000	       313 ns/op
```

**Comment by picatz** [comment]
**Note:** you can test the benchmarks like this:
```shell
$ go test -bench=.
```

**Comment by picatz** [comment]
We'll see how helpful the benchmarks are. 😂

**Pull request merged**
